### ISSUE TITLE
Error: TypeError: fetch failed

### ISSUE THREAD

**Issue by digitalboy** [SpellcraftAI/openai-streams#39]
Error: TypeError: fetch failed
[0]     at Object.fetch (node:internal/deps/undici/undici:11457:11)
[0]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[0]     at async s (file:///C:/Users/David/OneDrive/baikeAISomeTest/beikeadminui/node_modules/openai-streams/dist/lib/backoff.js:1:103)
[0]     at async Module.$ (file:///C:/Users/David/OneDrive/baikeAISomeTest/beikeadminui/node_modules/openai-streams/dist/lib/openai/edge.js:1:588)
[0]     at async C:\Users\David\OneDrive\baikeAISomeTest\beikeadminui\server.js:31:22 {
[0]   cause: ConnectTimeoutError: Connect Timeout Error
[0]       at onConnectTimeout (node:internal/deps/undici/undici:8422:28)
[0]       at node:internal/deps/undici/undici:8380:50
[0]       at Immediate._onImmediate (node:internal/deps/undici/undici:8409:37)
[0]       at process.processImmediate (node:internal/timers:476:21) {
[0]     code: 'UND_ERR_CONNECT_TIMEOUT'
[0]   }
[0] }

**Comment by ctjlewis** [comment]
Your connection timed out and the fetch failed. This was not an issue with the library.
