### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: require() of ES Module

### ISSUE THREAD

**Issue by Jeromearsene** [SpellcraftAI/openai-streams#52]
When i use lib, i have this error:

```
Error [ERR_REQUIRE_ESM]: require() of ES Module /Users/anonyme-user/Documents/Anonyme/anonyme-site/node_modules/openai-streams/dist/lib/openai/node.js from /Users/anonyme-user/Documents/Anonyme/anonyme-site/node_modules/openai-streams/node.cjs not supported.
Instead change the require of node.js in /Users/anonyme-user/Documents/Anonyme/anonyme-site/node_modules/openai-streams/node.cjs to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/Users/anonyme-user/Documents/Anonyme/anonyme-site/node_modules/openai-streams/node.cjs:1:18)
    at openai-streams/node (/Users/anonyme-user/Documents/Anonyme/anonyme-site/.next/server/pages/api/chat.js:62:18)
    at __webpack_require__ (/Users/anonyme-user/Documents/Anonyme/anonyme-site/.next/server/webpack-api-runtime.js:33:42)
    at eval (webpack-internal:///(api)/./src/pages/api/chat/index.ts:7:77)
    at __webpack_require__.a (/Users/anonyme-user/Documents/Anonyme/anonyme-site/.next/server/webpack-api-runtime.js:97:13)
    at eval (webpack-internal:///(api)/./src/pages/api/chat/index.ts:1:21)
    at (api)/./src/pages/api/chat/index.ts (/Users/anonyme-user/Documents/Anonyme/anonyme-site/.next/server/pages/api/chat.js:122:1)
    at __webpack_require__ (/Users/anonyme-user/Documents/Anonyme/anonyme-site/.next/server/webpack-api-runtime.js:33:42)
    at __webpack_exec__ (/Users/anonyme-user/Documents/Anonyme/anonyme-site/.next/server/pages/api/chat.js:172:39)
    at /Users/anonyme-user/Documents/Anonyme/anonyme-site/.next/server/pages/api/chat.js:173:28
    at Object.<anonymous> (/Users/anonyme-user/Documents/Anonyme/anonyme-site/.next/server/pages/api/chat.js:176:3)
    at DevServer.runApi (/Users/anonyme-user/Documents/Anonyme/anonyme-site/node_modules/next/dist/server/next-server.js:650:34)
    at DevServer.handleApiRequest (/Users/anonyme-user/Documents/Anonyme/anonyme-site/node_modules/next/dist/server/next-server.js:1181:21)
    at Object.fn (/Users/anonyme-user/Documents/Anonyme/anonyme-site/node_modules/next/dist/server/next-server.js:1124:46)
    at async Router.execute (/Users/anonyme-user/Documents/Anonyme/anonyme-site/node_modules/next/dist/server/router.js:315:32)
    at async DevServer.runImpl (/Users/anonyme-user/Documents/Anonyme/anonyme-site/node_modules/next/dist/server/base-server.js:601:29)
    at async DevServer.run (/Users/anonyme-user/Documents/Anonyme/anonyme-site/node_modules/next/dist/server/dev/next-dev-server.js:922:20)
    at async DevServer.handleRequestImpl (/Users/anonyme-user/Documents/Anonyme/anonyme-site/node_modules/next/dist/server/base-server.js:533:20) {
  digest: undefined
}
```

Version: 6.1.0

**Comment by ctjlewis** [comment]
Package is published as ES module. We pin legacy CJS at `openai-streams@cjs` if you can't transpile it yourself.
