### ISSUE TITLE
No fetch implementation found

### ISSUE THREAD

**Issue by codehruv** [SpellcraftAI/openai-streams#53]
Hi, 

Thanks for building this great project.

When I deployed the changes using the CJS implementation to my machine, it surfaced an error

Error: No fetch implementation found.

After doing some reading, it seems like I have to install the node-fetch library and import that into the openai-streams library fetch call somehow.

Is there a clean way for doing this?

**Comment by ctjlewis** [comment]
You have to install node-fetch and pass it in as `{ fetch: nodeFetch }`.

The library originally did this for you, but us having node-fetch in the bundle made it toxic for Edge environments so this is the only stable way.

It's tested against this though, so if you just pass in node-fetch you'll be OK.

**Comment by codehruv** [comment]
Thanks for the quick response.

That fixed the issue and it resurfaced another issue.

ReferenceError: ReadableStream is not defined

I couldn't find this in the tests file you shared. Is this a common error mode as well?

**Comment by ctjlewis** [comment]
You have to use `openai-streams/node` because you are on an old version of Node which does not have WHATWG ReadableStream available.

These are all just escape hatches, if you upgrade to Node 14+ (ideally 16+) they aren't needed.

**Comment by codehruv** [comment]
I'm currently using `openai-streams/node` itself. Is there a workaround to somehow get the ReadableStream into the code via another package (similar to the fetch solution)?

Thanks for the idea on upgrading node. You are right. I will make that upgrade soon.

**Comment by ctjlewis** [comment]
Sorry, that was actually my mistake, I edited my response - `ReadableStream` is available in Edge runtime/browser, but not Node.js, so `openai-streams/node` is needed.

If you're getting that error from `openai-streams/node`, that would be a bug.

**Comment by codehruv** [comment]
**Machine info**

Node version: v16.16.0
OS: Amazon Linux

**Code**

`
const { OpenAI } = require("openai-streams/node");
const fetch = require('cross-fetch');

// inside a function
const stream = await OpenAI(
                    "completions", 
                    {
                        prompt: requestBody.prompt,
                        model: requestBody.model,
                        max_tokens: requestBody.max_tokens,
                        temperature: requestBody.temperature,
                        top_p: requestBody.top_p,
                        frequency_penalty: requestBody.frequency_penalty,
                        presence_penalty: requestBody.presence_penalty,
                        stop: requestBody.stop
                    },
                    {
                        apiKey: openai_key,
                        fetch: fetch
                    });
                res.set({
                    'Content-Type': 'application/json; charset=utf-8',
                    'Transfer-Encoding': 'chunked'
                });
    
                // we need to track what was generated
                const chunks = [];
                var chunkText = "";
    
                for await (const chunk of stream) {
                    if (!chunk) continue;
                    chunkText = Buffer.from(chunk).toString("utf-8");
                    chunks.push(chunkText);
                    res.write(chunkText);
                }
`

**Error Message**

ReferenceError: ReadableStream is not defined                                                           
    at N (pwd/node_modules/openai-streams/dist/lib/streaming/streams.js:5:796)
    at V (pwd/node_modules/openai-streams/dist/lib/streaming/streams.js:5:1538)
    at D (pwd/node_modules/openai-streams/dist/lib/openai/edge.js:1:1692)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async u (pwd/node_modules/openai-streams/dist/lib/openai/node.js:1:675)

**Comment by codehruv** [comment]
Even after switching from `cross-fetch` to `node-fetch` the error persists

**Comment by codehruv** [comment]
Upgraded my node version to 17. There's some issue with moving to version 21 on my machine right now.

**Comment by ctjlewis** [comment]
> Upgraded my node version to 17. There's some issue with moving to version 21 on my machine right now.

Issue resolved? We'll get you up and running and add tests if needed

**Comment by ctjlewis** [comment]
If you're on 16, you can probably just use it normally again. See if `ReadableStream` is available:

```
$ node
Welcome to Node.js v18.8.0.
Type ".help" for more information.
> console.log(ReadableStream)
[class ReadableStream]
```

If you see it, just try the library how it comes out of the box, without custom `{ fetch }` or `openai-streams/node`etc:

```
$ node
Welcome to Node.js v18.8.0.
Type ".help" for more information.
> await import('openai-streams')
[Module: null prototype] {
  ChatParser: [AsyncGeneratorFunction: O],
  ChatStream: [Function: v],
  EventStream: [Function: c],
  LogprobsParser: [AsyncGeneratorFunction: l],
```

**Comment by codehruv** [comment]
The OS on my machine doesn't allow upgrading to a higher version of node at the moment.

Is there a way to resolve this issue without upgrading my OS?
